# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e47d73e04752146b41256cbfd0d4ca4335f16439689ffaf493570598d4f46ee41991151107718f0469c6c906ba7f4af1d9f1c73fe63b6d1aa7546b2ecc97c2d

test:
  secret_key_base: 500d85b9ddf093f6565188c587cab1484d165abf823d9567d38b3c1d315b845164fedcb15ec9d8715597bba1b3367fadee9593b3f58ebe4c7ecb55b0c00a7b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
